### ISSUE TITLE
Investigate where we can grab info about hot-tours

### ISSUE THREAD

**Issue by iTKerry** [itkerry-open-source/better-travel#1]
**Description**
We need to know from which sources we can collect info about tours.
Also we should know how we can extract it and what result type should looks like.

**Acceptable Criteria**
Please, find at least 3 sources from where we can collect data about relevant hot-tours and provide simple plan about how we can collect info from these sources. As a short conclusion: _provide the idea of how core logic should work_.

**Comment by iTKerry** [comment]
@Danisimogg write your result ideas here. We need to document it somewhere, so we can leave it here for a while

**Comment by Danisimogg** [comment]
@iTKerry  1) https://support.travelpayouts.com/hc/ru/articles/360022674591-API-%D0%BE%D1%82-Travelata-ru#tourslist - this is a free API, I think I need to know how to work with the API
2)parse instagram and facebook by tags
